substitutions:
  device_name: rc-test
  device_name_short: test
  wifi_ssid: wifissid
  wifi_pass: wifipass
  ota_pw: "s0/blwvQQhhdnOzHqrbixA=="
  api_key: "5Vq+Zr3gQqy9+kDYvEE7ZhdWtYRlyekqfW/igr+QcrQ="
  syslog_ip: !secret syslog_ip

esphome:
  name: $device_name
  comment: $device_name

esp32:
  board: esp32dev
  framework: 
    type: arduino
    
wifi:
  networks:
  - ssid: $wifi_ssid
    password: $wifi_pass

api:
  encryption:
    key: $api_key
  
ota:
  - platform: esphome
    password: !secret ota_pw

logger:
  level: VERBOSE

time:
  - platform: sntp
  id: my_time
  servers:
    - 0.pool.ntp.org
    - 1.pool.ntp.org

# syslog configuration. Defaults to udp/514
syslog:
  level: VERBOSE

# connectivity to the AC unit
uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  parity: EVEN

external_components:
  source:
    type: git
    url: https://github.com/beebop5/esphome-panasonic-ac
  components: [panasonic_ac]

# define select controls for the climate component
select:
  - platform: template
    name: "Panasonic AC Horizontal Swing"
    id: panasonic_ac_hswing
    options:
      - "Left"
      - "Centre Left"
      - "Centre"
      - "Centre Right"
      - "Right"
    initial_option: "Centre"
    optimistic: true

  - platform: template
    name: "Panasonic AC Vertical Swing"
    id: panasonic_ac_vswing
    options:
      - "Up"
      - "Mid Up"
      - "Mid"
      - "Mid Down"
      - "Down"
    initial_option: "Mid"
    optimistic: true

switch:
  - platform: restart
    name: "Restart"
  - platform: template
    name: "Panasonic AC NanoeX"
    id: panasonic_ac_nanoex
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true

climate:
  - platform: panasonic_ac
    name: $device_name_short
    outside_temperature:
      name: "Outside Temp"
    horizontal_swing_select_id: panasonic_ac_hswing
    vertical_swing_select_id: panasonic_ac_vswing
    nanoex_switch_id: panasonic_ac_nanoex