substitutions:
  device_name: test
  device_name_short: test
  wifi_ssid: "testwifi"
  wifi_pass: "test-password"

esphome:
  name: $device_name
  comment: $device_name

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  networks:
  - ssid: $wifi_ssid
    password: $wifi_pass

api:
  
ota:
  platform: esphome

logger:
  level: VERBOSE

# Configure a time source (SNTP is common)
time:
  - platform: sntp
    id: my_time
    servers:
    - 0.pool.ntp.org
    - 1.pool.ntp.org

# Requires ESPHome 1.15.0+ for the even parity option
uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  parity: EVEN
  rx_buffer_size: 1024

external_components:
  source:
    type: local
    path: components
  components: [panasonic_ac]

switch:
  - platform: restart
    name: "Restart"
  - platform: template
    name: "Test nanoeX"
    id: test_nanoex
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true

climate:
  - platform: panasonic_ac
    name: "Test Panasonic AC"
    
    # Test optional features
    outside_temperature:
      name: "Test Outside Temperature"

# Test select components
select:
  - platform: template
    name: "Test Horizontal Swing"
    id: test_horizontal_swing
    options:
      - "auto"
      - "left"
      - "left_center"
      - "center"
      - "right_center"
      - "right"
    initial_option: "auto"
    optimistic: true

  - platform: template
    name: "Test Vertical Swing"
    id: test_vertical_swing
    options:
      - "swing"
      - "auto"
      - "up"
      - "up_center"
      - "center"
      - "down_center"
      - "down"
    initial_option: "auto"
    optimistic: true
